
#  D令牌
#    说明：由于D令牌的随机码每30秒变换一次，
#    所以建议用户在第一次请求API的时候选择记住验证码。
#    选择记住验证码后，除了返回所请求的数据以外，
#    还会发一个名为’t’ + user_id 的cookie，
#    形如：t123456，该cookie的有效期为1个月，以后再请求API可以带上这个cookie，
#    而无须再提交login_code和login_remember参数。

protocol: https
host: dnsapi.cn
#port: 80
domain: c332030.com
preDomain: spring

common:
    userAgent: c332030 Web/1.0(c332030@qq.com)  # 程序英文名称/版本(联系邮箱)
    login_token: a004d83afce2617d9edf8d90ec8948b4  # 用于鉴权的 API Token
    format: json  # {json,xml} 返回的数据格式，可选，默认为xml，建议用json
    lang: cn  # {en,cn} 返回的错误语言，可选，默认为en，建议用cn
    error_on_empty: no  # {yes,no} 没有数据时是否返回错误，可选，默认为yes，建议用no
    user_id: c332030  # 用户的ID，可选，仅代理接口需要， 用户接口不需要提交此参数

    # 对于已经开启D令牌的用户，在请求API时需要增加如下两个参数
    login_code: 1  # D令牌生成的随机验证码，必选
    login_remember: yes  # {yes,no} 是否记住验证码，可选，默认为yes

url:
    version: Info.Version  # Api 版本
    user:
        detail: User.Detail  # 获取账户信息
        modify: User.Modify
    domain:
        create: DomainService.Create
        list: DomainService.List
        remove: DomainService.Remove
        info: DomainService.Info
        log: DomainService.Log
        search: DomainService.Searchenginepush  # 搜索引擎推送
        share: Domainshare.Create  # 域名共享
        shareList: Domainshare.List  # 共享列表
        modify: Domainshare.Modify  # 域名共享修改
    record:
        list: Record.List  # 记录列表
        modify: Record.Modify  # 记录修改
        remove: Record.Remove  # 删除记录
        updateDdns: Record.Ddns  # 更新动态 dns 记录
        setRemark: Record.Remark  # 设置备注
        setInfo: Record.Info  # 记录信息
        setStatus: Record.Status  # 设置记录状态

error: # 错误映射
    common:
        -1: 登陆失败
        -2: API使用超出限制
        -4: 不在代理名下 (仅用于代理接口)
        -3: 不是合法代理 (仅用于代理接口)
        -7: 无权使用此接口
        -8: 登录失败次数过多，帐号被暂时封禁
        -85: 帐号异地登录，请求被拒绝
        -99: 此功能暂停开放，请稍候重试
        1: 操作成功
        2: 只允许POST方法
        3: 未知错误
        6: 用户ID错误 (仅用于代理接口)
        7: 用户不在您名下 (仅用于代理接口)
        83: 该帐户已经被锁定，无法进行任何操作
        85: 该帐户开启了登录区域保护，当前IP不在允许的区域内

    # D 令牌 错误信息
    d:
        50: 您开启了D令牌，需要验证码
        51: 没有开启D令牌
        52: 验证码不正确
        53: 您已经开启了D令牌
        54: 域名所有者开启了D令牌，您也需要开启D令牌才能管理该域名

    # 记录
    record:
        "-15": 域名已被封禁
        "-7": 企业账号的域名需要升级才能设置
        "-8": 代理名下用户的域名需要升级才能设置
        6: 域名ID错误
        7: 不是域名所有者或没有权限
        8: 记录ID错误
        21: 域名被锁定
        22: 子域名不合法
        23: 子域名级数超出限制
        24: 泛解析子域名错误
        500025: A记录负载均衡超出限制
        500026: CNAME记录负载均衡超出限制
        26: 记录线路错误
        27: 记录类型错误
        29: TTL 值太小
        30: MX 值错误，1-20
        31: URL记录数超出限制
        32: NS 记录数超出限制
        33: AAAA 记录数超出限制
        35: 添加的IP不允许
        34: 记录值非法
        36: \@主机的NS纪录只能添加默认线路
        82: 不能添加黑名单中的IP