
prenum:

    # China mobile
    - 134
    - 135
    - 136
    - 137
    - 138
    - 139
    - 144
    - 147
    - 148
    - 150
    - 151
    - 152
    - 157
    - 158
    - 159
    - 181
    - 187
    - 188
    - 198

    # China unicom
    - 130
    - 131
    - 132
    - 133
    - 140
    - 146
    - 155
    - 156
    - 166
    - 171
    - 185
    - 186

    # China telecom
    - 133
    - 141
    - 153
    - 174
    - 177
    - 180
    - 189
    - 199

    # Vtitual
    - 170