
server:
    port: 8080

#    server:
#        port: 8080
        #    port: 443

        #    ssl:
        #        enabled: true
        #        key-store: classpath:config/ssl/c332030.com.jks

        #        key-store-password: 88714480
        #        key-password: 88714480
        #        key-alias: c332030.com
        #        key-store-type: PKCS12  # p12

        #        key-store: src/main/resources/config/ssl/ssl.keystore
        #        key-store-type: JKS  # *.keystore

        #        key-store-type: JKS


        #management:
        #    server:
        #        port: 8080
        #        ssl:
        #            enabled: true
        #            key-store: classpath:config/ssl/ssl.keystore
        #            key-password: secret

        #servlet:
        #context-path: /SpringBoot

spring:
    datasource:
        url: jdbc:mysql://mysql.server.c332030.com/SpringBoot?useSSL=false
        #url: jdbc:oracle:thin:@oracle.server.c332030.com:1521:orcl
        username: root
        password: 88714480
        type: com.alibaba.druid.pool.DruidDataSource
        #        driver-class-name: oracle.jdbc.OracleDriver
        driver-class-name: com.mysql.jdbc.Driver


        #        stat sql监控
        #        wall 防火墙监控
        #        log4j 日志监控
        #        mergeSql 合并非传参的sql，select * from t where id = 1  --》 select * from t where id = ?
        filters: stat,wall,log4j,mergeSql

        #        合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true

    #    thymeleaf:
    #        prefix: classpath:templates/
    #        check-template-location: true
    #        suffix: .html
    #        mode: HTML5
    #        mode: HTML
    #        encoding: UTF-8
    #        cache: false
    #        enabled: false

    redis:
        database: 5
        host: redis.server.c332030.com
        password: 88714480
        port: 6379
        timeout: 3000
        pool:
            # 连接池中的最大空闲连接
            max-idle: 100
            # 连接池中的最小空闲连接
            min-idle: 10
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: -1
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1

    mvc:
        view:
            suffix: .html
            prefix: /

    freemarker:
        cache: false

mybatis:
    type-aliases-package: c332030.passport.model


    #   mapper-locations: classpath: mapping/*.xml
    #     mapper-locations: classpath: c332030/SpringBoot/Web/Mapper/*.xml
    #  MyBatis 别名
    # 自动更新表结构
#    table: # create（该操作会破坏原有数据）, update, none
#        auto: update
#    model:
#        pack: c332030.login.model
#    database:
#        type: mysql




#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql

# /actuator/health 查看健康状态
# /actuator/shutdown 关闭网站
#endpoints:
#    enabled: true
#    sensitive:
#    info:
#        enabled: true
#    beans:
#        id: springbeans
#        sensitive: false
#    shutdown:
#        enabled: true



# 打印出 spring 运行日志，如：动态代理，注解处理
#debug: true

# trace < debug < info < warn < Error < Fatal
logging:
    # 日志文件位置
    file: ./passport/log/passport.log

    level:
        # 打印所有 debug 以上的日志
#        root: debug

        # 当前包中日志最低级别
        c332030: debug

